---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelines-demos-push
  annotations:
    # The event we are targeting (ie: pull_request, push)
    pipelinesascode.tekton.dev/on-event: "[push]"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"

    # Fetch the git-clone task from hub, we are able to reference it with taskRef
    pipelinesascode.tekton.dev/task: "[git-clone]"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)

      - name: build-image
        taskRef:
          name: s2i-go
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
        params:
          - name: TLSVERIFY
            value: "false"
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/pipelines-demos/sample-go
          - name: PATH_CONTEXT
            value: sample-go/source-build/
        runAfter:
          - fetch-repository

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
